.\" Copyright (C) 2005-2013  Dmitry V. Levin <ldv@altlinux.org>
.\"
.\" Additional documentation for the faketime command.
.\"
.\" This file is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.

[NAME]
\fBfaketime\fR \- execute program with changed notion of system time

[SEE ALSO]
.BR date (1),
.BR touch (1),
info "\fBDate input formats\fR".
